/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.figurasgeometrica.gui;

import com.example.figurasgeometrica.Circulo;
import com.example.figurasgeometrica.Cuadrado;

/**
 *
 * @author jhguerra
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        ocultarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_figure = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rb_cuadrado = new javax.swing.JRadioButton();
        rb_circulo = new javax.swing.JRadioButton();
        rb_triangulo_equilatero = new javax.swing.JRadioButton();
        rb_otro_triangulo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jp_cuadrado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_lado_cuadrado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_calcular_cuadrado = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lbl_perimetro = new javax.swing.JLabel();
        lbl_area = new javax.swing.JLabel();
        jp_circulo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_radio_circulo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_calcular_circulo = new javax.swing.JButton();
        jp_otro_triangulo = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_lado_triangulo_1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_calcular_otro_triangulo = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_lado_triangulo_2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_lado_triangulo_3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jp_triangulo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_lado_triangulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_calcular_triangulo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 247, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtro figura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), java.awt.Color.gray)); // NOI18N
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        group_figure.add(rb_cuadrado);
        rb_cuadrado.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rb_cuadrado.setText("Cuadrado");
        rb_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cuadradoActionPerformed(evt);
            }
        });

        group_figure.add(rb_circulo);
        rb_circulo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rb_circulo.setText("Circulo");
        rb_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_circuloActionPerformed(evt);
            }
        });

        group_figure.add(rb_triangulo_equilatero);
        rb_triangulo_equilatero.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rb_triangulo_equilatero.setText("Triangulo Equilatero");
        rb_triangulo_equilatero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_triangulo_equilateroActionPerformed(evt);
            }
        });

        group_figure.add(rb_otro_triangulo);
        rb_otro_triangulo.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        rb_otro_triangulo.setText("Otro Triangulo");
        rb_otro_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_otro_trianguloActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleccione la figura:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_otro_triangulo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_cuadrado)
                            .addComponent(rb_circulo)
                            .addComponent(rb_triangulo_equilatero))
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rb_cuadrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_circulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_triangulo_equilatero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_otro_triangulo)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_cuadrado.setBackground(new java.awt.Color(208, 227, 223));
        jp_cuadrado.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuadrado "));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setText("Ingresar valor del lado: ");

        txt_lado_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado_cuadradoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("cm");

        btn_calcular_cuadrado.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btn_calcular_cuadrado.setText("Calcular");
        btn_calcular_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_cuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_cuadradoLayout = new javax.swing.GroupLayout(jp_cuadrado);
        jp_cuadrado.setLayout(jp_cuadradoLayout);
        jp_cuadradoLayout.setHorizontalGroup(
            jp_cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_lado_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_calcular_cuadrado)
                .addGap(51, 51, 51))
        );
        jp_cuadradoLayout.setVerticalGroup(
            jp_cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_lado_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_calcular_cuadrado))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(191, 147, 142));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado "));

        lbl_perimetro.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbl_perimetro.setText("Perimetro: 0.0");

        lbl_area.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lbl_area.setText("Area: 0.0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_area)
                    .addComponent(lbl_perimetro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(lbl_area)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_perimetro)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jp_circulo.setBackground(new java.awt.Color(208, 96, 195));
        jp_circulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Circulo"));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("Ingresar el radio: ");

        txt_radio_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_radio_circuloActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("cm");

        btn_calcular_circulo.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btn_calcular_circulo.setText("Calcular");
        btn_calcular_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_circuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_circuloLayout = new javax.swing.GroupLayout(jp_circulo);
        jp_circulo.setLayout(jp_circuloLayout);
        jp_circuloLayout.setHorizontalGroup(
            jp_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_circuloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_radio_circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(btn_calcular_circulo)
                .addGap(51, 51, 51))
        );
        jp_circuloLayout.setVerticalGroup(
            jp_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_circuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_radio_circulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btn_calcular_circulo))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jp_otro_triangulo.setBackground(new java.awt.Color(153, 153, 0));
        jp_otro_triangulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Otro Triangulo"));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel7.setText("Ingresar valor del lado #1: ");

        txt_lado_triangulo_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado_triangulo_1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel8.setText("cm");

        btn_calcular_otro_triangulo.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btn_calcular_otro_triangulo.setText("Calcular");
        btn_calcular_otro_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_otro_trianguloActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel11.setText("Ingresar valor del lado #2: ");

        txt_lado_triangulo_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado_triangulo_2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setText("cm");

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel13.setText("Ingresar valor del lado #3: ");

        txt_lado_triangulo_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado_triangulo_3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel14.setText("cm");

        javax.swing.GroupLayout jp_otro_trianguloLayout = new javax.swing.GroupLayout(jp_otro_triangulo);
        jp_otro_triangulo.setLayout(jp_otro_trianguloLayout);
        jp_otro_trianguloLayout.setHorizontalGroup(
            jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_lado_triangulo_3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                        .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_lado_triangulo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_lado_triangulo_2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(55, 55, 55)
                                .addComponent(btn_calcular_otro_triangulo)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jp_otro_trianguloLayout.setVerticalGroup(
            jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_lado_triangulo_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_lado_triangulo_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btn_calcular_otro_triangulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_lado_triangulo_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jp_triangulo.setBackground(new java.awt.Color(153, 255, 204));
        jp_triangulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Triangulo Equilatero"));

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel9.setText("Ingresar valor del lado: ");

        txt_lado_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado_trianguloActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel10.setText("cm");

        btn_calcular_triangulo.setFont(new java.awt.Font("Segoe UI Black", 2, 12)); // NOI18N
        btn_calcular_triangulo.setText("Calcular");
        btn_calcular_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcular_trianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_trianguloLayout = new javax.swing.GroupLayout(jp_triangulo);
        jp_triangulo.setLayout(jp_trianguloLayout);
        jp_trianguloLayout.setHorizontalGroup(
            jp_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_trianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_lado_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_calcular_triangulo)
                .addGap(51, 51, 51))
        );
        jp_trianguloLayout.setVerticalGroup(
            jp_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_trianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_lado_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btn_calcular_triangulo))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_cuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_circulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_otro_triangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_triangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_circulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_otro_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cuadradoActionPerformed
        jp_cuadrado.setVisible(true);
        jp_circulo.setVisible(false);
        jp_triangulo.setVisible(false);
        jp_otro_triangulo.setVisible(false);
    }//GEN-LAST:event_rb_cuadradoActionPerformed

    private void txt_lado_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado_cuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado_cuadradoActionPerformed

    private void btn_calcular_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_cuadradoActionPerformed
        double parametroLado = Double.parseDouble(txt_lado_cuadrado.getText());
        Cuadrado cuadrado = new Cuadrado(parametroLado, "Cuadrado");
        cuadrado.setArea();
        cuadrado.setPerimetro();
        
        lbl_area.setText("Area: " + cuadrado.getArea());
        lbl_perimetro.setText("Perimetro: " + cuadrado.getPerimetro());
        
    }//GEN-LAST:event_btn_calcular_cuadradoActionPerformed

    private void txt_radio_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_radio_circuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_radio_circuloActionPerformed

    private void btn_calcular_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_circuloActionPerformed
       double parametroRadio = Double.parseDouble(txt_radio_circulo.getText());
        Circulo circulo = new Circulo(parametroRadio, "Circulo");
        circulo.setArea();
        circulo.setPerimetro();
        lbl_area.setText("Area: " + circulo.getArea());
        lbl_perimetro.setText("Perimetro: " + circulo.getPerimetro());
    }//GEN-LAST:event_btn_calcular_circuloActionPerformed

    private void txt_lado_triangulo_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado_triangulo_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado_triangulo_1ActionPerformed

    private void btn_calcular_otro_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_otro_trianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calcular_otro_trianguloActionPerformed

    private void txt_lado_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado_trianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado_trianguloActionPerformed

    private void btn_calcular_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcular_trianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calcular_trianguloActionPerformed

    private void txt_lado_triangulo_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado_triangulo_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado_triangulo_2ActionPerformed

    private void txt_lado_triangulo_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado_triangulo_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado_triangulo_3ActionPerformed

    private void rb_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_circuloActionPerformed
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(true);
        jp_triangulo.setVisible(false);
        jp_otro_triangulo.setVisible(false);
    }//GEN-LAST:event_rb_circuloActionPerformed

    private void rb_triangulo_equilateroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_triangulo_equilateroActionPerformed
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(false);
        jp_triangulo.setVisible(true);
        jp_otro_triangulo.setVisible(false);
    }//GEN-LAST:event_rb_triangulo_equilateroActionPerformed

    private void rb_otro_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_otro_trianguloActionPerformed
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(false);
        jp_triangulo.setVisible(false);
        jp_otro_triangulo.setVisible(true);
    }//GEN-LAST:event_rb_otro_trianguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular_circulo;
    private javax.swing.JButton btn_calcular_cuadrado;
    private javax.swing.JButton btn_calcular_otro_triangulo;
    private javax.swing.JButton btn_calcular_triangulo;
    private javax.swing.ButtonGroup group_figure;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jp_circulo;
    private javax.swing.JPanel jp_cuadrado;
    private javax.swing.JPanel jp_otro_triangulo;
    private javax.swing.JPanel jp_triangulo;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_perimetro;
    private javax.swing.JRadioButton rb_circulo;
    private javax.swing.JRadioButton rb_cuadrado;
    private javax.swing.JRadioButton rb_otro_triangulo;
    private javax.swing.JRadioButton rb_triangulo_equilatero;
    private javax.swing.JTextField txt_lado_cuadrado;
    private javax.swing.JTextField txt_lado_triangulo;
    private javax.swing.JTextField txt_lado_triangulo_1;
    private javax.swing.JTextField txt_lado_triangulo_2;
    private javax.swing.JTextField txt_lado_triangulo_3;
    private javax.swing.JTextField txt_radio_circulo;
    // End of variables declaration//GEN-END:variables

    private void ocultarComponentes() {
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(false);
        jp_triangulo.setVisible(false);
        jp_otro_triangulo.setVisible(false);
    }
}
